# Generated by Django 2.1.4 on 2019-12-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_training', models.BooleanField(default=False, help_text='Is this a training campaign for analysts')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('complete', 'complete')], max_length=10)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Country')),
            ],
        ),
        migrations.CreateModel(
            name='drugReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, null=True)),
                ('dossage', models.CharField(max_length=10, null=True)),
                ('inn', models.CharField(help_text='Active ingredient in the drug. eg. paracetamol', max_length=300, null=True)),
                ('therapeutic_purpose', models.TextField(null=True)),
                ('company', models.ForeignKey(help_text='Manufacturing company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Company')),
                ('form', models.ForeignKey(help_text='liquid,tablet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.drugForm')),
            ],
        ),
        migrations.CreateModel(
            name='therapeuticClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=200, null=True)),
                ('anatomical_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.anatomicalClass')),
            ],
        ),
    ]
