# Generated by Django 2.1.4 on 2019-12-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_city_drugreference_therapeuticclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='chemicalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=200, null=True)),
                ('therapeutic_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.therapeuticClass')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(help_text='City in which Pharmacy can be found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.City')),
            ],
        ),
    ]
