# Generated by Django 2.1.4 on 2019-12-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_chemicalclass_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=100, null=True)),
                ('inncode', models.CharField(max_length=200, null=True)),
                ('chemical_class', models.ForeignKey(help_text='Which chemical code does this substance match to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.chemicalClass')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(help_text='mobile phone number of the followed pharmacist (vendor)', max_length=14, null=True)),
                ('detailed_address', models.TextField(help_text='Make this detailed to easily find pharmacy', null=True)),
                ('pharmacist_first_name', models.CharField(max_length=150, null=True)),
                ('pharmacist_last_name', models.CharField(max_length=150, null=True)),
                ('average_patients_per_day', models.IntegerField(default=0, help_text='Average number of patients visiting the pharmacy per day')),
                ('insurance_convention', models.CharField(choices=[('Private Insurance', 'Private Insurance'), ('Public Insurance', 'Public Insurance'), ('No Insurance', 'No Insurance'), ('Undetermined', 'Undetermined')], max_length=100, null=True)),
                ('pharmacy_standard', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C', 'C')], max_length=5, null=True)),
                ('district_social_standard', models.CharField(choices=[('Upper-Top quartile', 'Upper-Top quartile'), ('Average-2nd quartile', 'Average-2nd quartile'), ('Average-3rd quartile', 'Average-3rd quartile'), ('Lower-4th quartile', 'Lower-4th quartile')], max_length=50, null=True)),
                ('district_profile', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Other', 'Other')], max_length=20, null=True)),
                ('conselling', models.BooleanField(default=False)),
                ('computerized', models.BooleanField(default=False)),
                ('staff_mostly_followed', models.CharField(choices=[('Owner', 'Owner'), ('Pharmacist in chief', 'Pharmacist in chief'), ('Pharmacist assistant', 'Pharmacist assistant'), ('Technician', 'Technician'), ('Vendor', 'Vendor')], max_length=50, null=True)),
                ('staff_mostly_present', models.CharField(choices=[('Owner', 'Owner'), ('Pharmacist in chief', 'Pharmacist in chief'), ('Pharmacist assistant', 'Pharmacist assistant'), ('Technician', 'Technician'), ('Vendor', 'Vendor')], max_length=50, null=True)),
                ('dependent_on_hospital', models.BooleanField(default=False)),
                ('comments', models.TextField(help_text='Any other things we should take notice of...', null=True)),
                ('area_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.District')),
                ('tests_available', models.ManyToManyField(to='campaigns.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
