# Generated by Django 2.1.4 on 2019-12-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_scheme', models.CharField(choices=[('Private Insurance', 'Private Insurance'), ('Public Insurance', 'Public Insurance'), ('No Insurance', 'No Insurance'), ('Undetermined', 'Undetermined')], max_length=100, null=True)),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Basket')),
            ],
        ),
    ]
