# Generated by Django 2.1.4 on 2019-12-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_request', models.CharField(choices=[('brand patient', 'brand patient'), ('brand prescription', 'brand prescription'), ('inn patient', 'inn patient'), ('inn prescription', 'inn prescription')], help_text='Who started the request?', max_length=15, null=True)),
                ('drug_sold', models.CharField(help_text='brand name of drug that has been sold?', max_length=200)),
                ('sale_driver', models.CharField(choices=[('Patient', 'Patient'), ('Pharmacist', 'Pharmacist'), ('Prescriber', 'Prescriber')], help_text='Who makes the final selection for the purchased product?', max_length=15, null=True)),
                ('switched', models.BooleanField(default=False, help_text='Was there a switch?')),
                ('leaked', models.BooleanField(default=False, help_text='Was there a leak?')),
                ('product_switched_or_leaked', models.CharField(help_text='What product was switched or leaked?', max_length=200)),
                ('reason_for_switch_or_leak', models.CharField(choices=[('Not available', 'Not available'), ('Price', 'Price'), ('Therapeutic Reason', 'Therapeutic Reason'), ('Other Reason', 'Other Reason')], help_text='Why was there a switch or a leak?', max_length=50, null=True)),
                ('division', models.CharField(choices=[('unit', 'unit'), ('blister', 'blister'), ('box', 'box'), ('blister+unit', 'blister+unit'), ('box+unit', 'box+unit'), ('box+blister', 'box+blister')], help_text='Was the whole box sold? How was it divided?', max_length=50, null=True)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Basket')),
                ('form_sold', models.ForeignKey(help_text='What form of drug was sold? liquid,tablet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.drugForm')),
            ],
        ),
    ]
