# Generated by Django 2.1.4 on 2020-01-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Upper-Top quartile', 'Upper-Top quartile'), ('Average-2nd quartile', 'Average-2nd quartile'), ('Average-3rd quartile', 'Average-3rd quartile'), ('Lower-4th quartile', 'Lower-4th quartile')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unit', 'unit'), ('blister', 'blister'), ('box', 'box'), ('blister+unit', 'blister+unit'), ('box+unit', 'box+unit'), ('box+blister', 'box+blister')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Private Insurance', 'Private Insurance'), ('Public Insurance', 'Public Insurance'), ('No Insurance', 'No Insurance'), ('Undetermined', 'Undetermined')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacologicalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=200, null=True)),
                ('chemical_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.chemicalClass')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C', 'C')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('brand patient', 'brand patient'), ('brand prescription', 'brand prescription'), ('inn patient', 'inn patient'), ('inn prescription', 'inn prescription')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Patient', 'Patient'), ('Pharmacist', 'Pharmacist'), ('Prescriber', 'Prescriber')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFollowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Owner', 'Owner'), ('Pharmacist in chief', 'Pharmacist in chief'), ('Pharmacist assistant', 'Pharmacist assistant'), ('Technician', 'Technician'), ('Vendor', 'Vendor')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Not available', 'Not available'), ('Price', 'Price'), ('Therapeutic Reason', 'Therapeutic Reason'), ('Other Reason', 'Other Reason')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='anatomicalclass',
            options={'verbose_name_plural': 'anatomical classes'},
        ),
        migrations.AlterModelOptions(
            name='therapeuticclass',
            options={'verbose_name_plural': 'therapeutic classes'},
        ),
    ]
