# Generated by Django 2.1.4 on 2020-04-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_session_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='session',
            name='pharmacy',
            field=models.ForeignKey(help_text='Where this basket of drugs is being created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Pharmacy'),
        ),
    ]
