# Generated by Django 2.1.4 on 2020-04-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20200420_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('active', models.CharField(max_length=10, null=True)),
                ('stage', models.CharField(max_length=10, null=True)),
                ('concerns', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('whatsapp_phone', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='campaigns.Parent'),
        ),
    ]
