# Generated by Django 2.1.4 on 2020-04-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20200420_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
    ]
