# Generated by Django 2.1.4 on 2020-04-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_remove_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='active',
        ),
    ]
