# Generated by Django 2.1.4 on 2020-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20200503_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='initial_request',
            field=models.CharField(choices=[('brand patient', 'brand patient'), ('brand prescription', 'brand prescription'), ('inn patient', 'inn patient'), ('inn prescription', 'inn prescription')], help_text='Who started the request?', max_length=30, null=True),
        ),
    ]
